In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

NameError: name 'a' is not defined

In [ ]:
type(a)

In [3]:
a=5


In [4]:
type (a)

int

In [5]:
a = "TheAtifWaheed"

In [6]:
type (a)

str

In [7]:
len(a)

13

In [8]:
print(a)

TheAtifWaheed


In [9]:
a = [1,2,3]

In [10]:
type(a)

list

In [11]:
a[0]

1

In [12]:
a[1]

2

In [13]:
a[10]

IndexError: list index out of range

In [14]:
a = [1,20.5,"TheAtifWaheed"]

In [15]:
type(a)

list

In [16]:
print(a)

[1, 20.5, 'TheAtifWaheed']


In [17]:
print(a[0]+a[1])

21.5


In [21]:
print(a[2])

TheAtifWaheed


In [22]:
string = "TheAtifWaheed"

In [23]:
a = np.array(a)

In [24]:
a[a>0]

TypeError: '>' not supported between instances of 'numpy.ndarray' and 'int'

In [6]:
a = [1,2,3,4,5,6,7,8,9]

In [27]:
a = np.array(a)

In [28]:
a[a>3]

array([4, 5, 6, 7, 8, 9])

In [29]:
print(a[a>3])

[4 5 6 7 8 9]


In [32]:
b = [False,True,False,True,False,True,False,True,False]

In [33]:
a[b]

array([2, 4, 6, 8])

In [34]:
a[len(a)-1]

9

In [35]:
a[-1]

9

In [36]:
a[-(len(a))]

1

In [37]:
a[2:6]

array([3, 4, 5, 6])

In [40]:
a.append(10)

In [41]:
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [42]:
a.extend([10,11,12])

In [43]:
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 11, 12]


In [44]:
a.pop()


12

In [45]:
a.append(12)

In [46]:
a.remove(10)

In [47]:
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [48]:
Arr = [1,2,3,4,5,"TheAtif",2.5]

In [49]:
print(Arr)

[1, 2, 3, 4, 5, 'TheAtif', 2.5]


In [50]:
a.pop()

12

In [52]:
a.pop()

11

In [53]:
a.extend([11,12])

In [5]:
print(a)

NameError: name 'a' is not defined

In [55]:
Arr.pop()

2.5

In [56]:
Arr.pop()

'TheAtif'

In [59]:
print(Arr)

[1, 2, 'TheAtifWaheed', 4, 5]


In [58]:
Arr[2] = "TheAtifWaheed"

In [60]:
string.lower()

'theatifwaheed'

In [61]:
string.upper()

'THEATIFWAHEED'

In [64]:
print(string)

theatifwaheed


In [63]:
string = string.lower()

In [67]:
string[::-1]

'deehawfitaeht'

In [69]:
string[::-1]

'deehawfitaeht'

In [70]:
st = "TheAtifWaheed"

In [71]:
st = st[::-1]

In [72]:
st


'deehaWfitAehT'

In [73]:
st = st[::-1]

In [74]:
st

'TheAtifWaheed'

In [75]:
st.replace('A')

TypeError: replace expected at least 2 arguments, got 1

In [78]:
st.find('i')

5

In [80]:
st.replace('e','3')

'Th3AtifWah33d'

In [81]:
st

'TheAtifWaheed'

In [82]:
appos = "Atif's Website"

In [83]:
appos

"Atif's Website"

In [86]:
st

'theatifwaheed'

In [85]:
st = st.lower()

In [89]:
st.capitalize()

'Theatifwaheed'

In [90]:
intro = "my name is the atif waheed"

In [91]:
intro.capitalize()

'My name is the atif waheed'

In [92]:
intro.casefold()

'my name is the atif waheed'

In [95]:
intro.isdigit()
intro.isalpha()

False

In [96]:
intro.isalpha()

False

In [98]:
intro.isalnum()

False

In [99]:
intro.split('w')

['my name is the atif ', 'aheed']

In [100]:
intro.split(' ')

['my', 'name', 'is', 'the', 'atif', 'waheed']

In [101]:
intro.startswith('m')

True

In [103]:
intro.count('e')

4

In [107]:
a = 5
b = 7

In [115]:
if (a > b):
    print("Wow")
elif b == a:
    print("Equal")
else:
    print("NoWay")
    if a == 5:
        print("Five")

NoWay
Five


In [121]:
a = [1,2,3,4,5,6,7,8,9,5]
if 5 not in a:
    print("Great Work")
else:
    print("Not good Work")

Not good Work


In [119]:
a.index(5)

4

In [123]:
s = "theAtifWaheed"

In [126]:
for i in s:
    print(i.upper())

T
H
E
A
T
I
F
W
A
H
E
E
D


In [132]:
_list = list(range(1,10,2))

In [135]:
_list

[1, 3, 5, 7, 9]

In [130]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


In [131]:
list(range(0))

[]

In [134]:
len(_list)

5

In [ ]:
i=0
while i<10:
    print(i)
    i=i+1